# Travis CI YAML file. See
# http://docs.travis-ci.com/user/getting-started/#Step-three%3A-Add-.travis.yml-file-to-your-repository

language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install --use-mirrors -e .
# command to run tests, e.g. python setup.py test
script:  nosetests --exe
matrix:
  allow_failures:
    - env: REQFILE=requirements.txt

